using FluentAssertions;
using Xunit;

namespace GameTeam.Codegen.Tests;

/// <summary>Integration: sinh từ spec THẬT của repo → khớp DTO/enum nền của GameTeam.Contracts.</summary>
public class RealSpecTests
{
    private static IReadOnlyList<GeneratedFile> Real() =>
        CodegenRunner.Generate(File.ReadAllText(TestPaths.RealOpenApi), "shared/contracts/openapi.json");

    private static string Content(IReadOnlyList<GeneratedFile> files, string name) =>
        files.Single(f => f.FileName == name).Content;

    [Fact]
    public void Generates_six_enums_and_eight_dtos()
    {
        IReadOnlyList<GeneratedFile> files = Real();

        files.Select(f => f.FileName).Should().BeEquivalentTo(
            "faction.gd", "class.gd", "element.gd", "role.gd", "rarity.gd", "currency.gd",
            "auth_guest_request.gd", "auth_guest_response.gd", "config_bundle_dto.gd", "config_version.gd",
            "error_envelope.gd", "error_response.gd", "health_response.gd", "profile_dto.gd");
    }

    [Fact]
    public void Rarity_matches_contract_numeric_values()
    {
        string gd = Content(Real(), "rarity.gd");
        gd.Should().Contain("\tNONE = 0,");
        gd.Should().Contain("\tTHREE = 3,");
        gd.Should().Contain("\tFOUR = 4,");
        gd.Should().Contain("\tFIVE = 5,");
    }

    [Fact]
    public void ProfileDto_maps_fields_to_snake_case_typed()
    {
        string gd = Content(Real(), "profile_dto.gd");
        gd.Should().Contain("class_name ProfileDto");
        gd.Should().Contain("var player_id: String");
        gd.Should().Contain("var display_name: String");
        gd.Should().Contain("var level: int");
        gd.Should().Contain("var schema_version: int");
    }

    [Fact]
    public void AuthGuestRequest_nullable_device_id_is_untyped()
    {
        string gd = Content(Real(), "auth_guest_request.gd");
        gd.Should().Contain("## wire: deviceId | nullable");
        gd.Should().Contain("var device_id\n");
    }

    [Fact]
    public void ConfigBundleDto_references_nested_generated_type()
    {
        string gd = Content(Real(), "config_bundle_dto.gd");
        gd.Should().Contain("var version: ConfigVersion");
    }

    [Fact]
    public void Every_file_has_autogenerated_header_with_source()
    {
        foreach (GeneratedFile file in Real())
        {
            file.Content.Should().StartWith("# AUTO-GENERATED — DO NOT EDIT.");
            file.Content.Should().Contain("# Source: shared/contracts/openapi.json");
            file.Content.Should().Contain("# Generated by: shared/codegen");
        }
    }
}
