// <auto-generated />
using System;
using GameTeam.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameTeam.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameTeam.Domain.Accounts.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("GameTeam.Domain.Battles.BattleRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AttemptId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("attempt_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Log")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("log");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Rounds")
                        .HasColumnType("integer")
                        .HasColumnName("rounds");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.Property<string>("StageId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stage_id");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "AttemptId")
                        .IsUnique()
                        .HasDatabaseName("ix_battle_records_profile_attempt");

                    b.ToTable("battle_records", (string)null);
                });

            modelBuilder.Entity("GameTeam.Domain.Economy.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_wallets_profile_id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("GameTeam.Domain.Heroes.OwnedHero", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("HeroId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hero_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("Stars")
                        .HasColumnType("integer")
                        .HasColumnName("stars");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_owned_heroes_profile_id");

                    b.HasIndex("ProfileId", "HeroId")
                        .IsUnique()
                        .HasDatabaseName("ix_owned_heroes_profile_id_hero_id");

                    b.ToTable("owned_heroes", (string)null);
                });

            modelBuilder.Entity("GameTeam.Domain.Profiles.PlayerProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("account_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_profiles_account_id");

                    b.ToTable("player_profiles", (string)null);
                });

            modelBuilder.Entity("GameTeam.Domain.Teams.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_profile_id");

                    b.ToTable("teams", (string)null);
                });

            modelBuilder.Entity("GameTeam.Infrastructure.Persistence.ConfigBundleRecord", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checksum");

                    b.Property<string>("ConfigVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("config_version");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("generated_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.HasKey("Id");

                    b.HasIndex("ConfigVersion")
                        .IsUnique()
                        .HasDatabaseName("ix_config_bundles_config_version");

                    b.ToTable("config_bundles", (string)null);
                });

            modelBuilder.Entity("GameTeam.Infrastructure.Persistence.ConfigCurrentPointer", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("integer")
                        .HasColumnName("current_version");

                    b.HasKey("Id");

                    b.ToTable("config_current", (string)null);
                });

            modelBuilder.Entity("GameTeam.Infrastructure.Persistence.SchemaMetadata", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.ToTable("schema_metadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            Version = 1
                        });
                });

            modelBuilder.Entity("GameTeam.Domain.Battles.BattleRecord", b =>
                {
                    b.HasOne("GameTeam.Domain.Profiles.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameTeam.Domain.Battles.BattleReward", "Rewards", b1 =>
                        {
                            b1.Property<Guid>("BattleRecordId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("Amount")
                                .HasColumnType("integer")
                                .HasAnnotation("Relational:JsonPropertyName", "amount");

                            b1.Property<string>("RefId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "ref_id");

                            b1.Property<string>("RewardType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "reward_type");

                            b1.HasKey("BattleRecordId", "__synthesizedOrdinal");

                            b1.ToTable("battle_records");

                            b1.ToJson("rewards");

                            b1.WithOwner()
                                .HasForeignKey("BattleRecordId");
                        });

                    b.Navigation("Rewards");
                });

            modelBuilder.Entity("GameTeam.Domain.Economy.Wallet", b =>
                {
                    b.HasOne("GameTeam.Domain.Profiles.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameTeam.Domain.Economy.WalletBalance", "Balances", b1 =>
                        {
                            b1.Property<Guid>("WalletId")
                                .HasColumnType("uuid");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<long>("Amount")
                                .HasColumnType("bigint")
                                .HasAnnotation("Relational:JsonPropertyName", "amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasAnnotation("Relational:JsonPropertyName", "currency");

                            b1.HasKey("WalletId", "__synthesizedOrdinal");

                            b1.ToTable("wallets");

                            b1.ToJson("balances");

                            b1.WithOwner()
                                .HasForeignKey("WalletId");
                        });

                    b.Navigation("Balances");
                });

            modelBuilder.Entity("GameTeam.Domain.Heroes.OwnedHero", b =>
                {
                    b.HasOne("GameTeam.Domain.Profiles.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTeam.Domain.Profiles.PlayerProfile", b =>
                {
                    b.HasOne("GameTeam.Domain.Accounts.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GameTeam.Domain.Teams.Team", b =>
                {
                    b.HasOne("GameTeam.Domain.Profiles.PlayerProfile", null)
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("GameTeam.Domain.Teams.TeamSlot", "Slots", b1 =>
                        {
                            b1.Property<Guid>("team_id")
                                .HasColumnType("uuid")
                                .HasColumnName("team_id");

                            b1.Property<int>("SlotIndex")
                                .HasColumnType("integer")
                                .HasColumnName("slot_index");

                            b1.Property<string>("HeroId")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("hero_id");

                            b1.HasKey("team_id", "SlotIndex");

                            b1.ToTable("team_slots", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("team_id");
                        });

                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
