using System.Text;

namespace GameTeam.Codegen;

/// <summary>
/// Sinh nội dung file GDScript (enum + DTO) từ model. Toàn bộ dùng '\n' (LF) + newline cuối,
/// KHÔNG timestamp/đường dẫn máy → deterministic + idempotent. Header cảnh báo "DO NOT EDIT".
/// </summary>
public static class GdEmitter
{
    private const string Lf = "\n";

    /// <summary>Header cảnh báo chung — nêu rõ nguồn contract + không sửa tay.</summary>
    public static string Header(string sourceLabel, string schemaName)
    {
        StringBuilder sb = new();
        sb.Append("# AUTO-GENERATED — DO NOT EDIT.").Append(Lf);
        sb.Append("# Source: ").Append(sourceLabel).Append(" (schema: ").Append(schemaName).Append(')').Append(Lf);
        sb.Append("# Generated by: shared/codegen").Append(Lf);
        sb.Append("# Đổi contract? Sửa server/GameTeam.Contracts → rebuild (regenerate openapi.json) → chạy shared/codegen/run.sh.").Append(Lf);
        return sb.ToString();
    }

    /// <summary>Enum → file <c>class_name &lt;Name&gt;</c> + enum không tên (member truy cập <c>&lt;Name&gt;.MEMBER</c>).</summary>
    public static string EmitEnum(EnumSchema schema, string sourceLabel)
    {
        StringBuilder sb = new();
        sb.Append(Header(sourceLabel, schema.Name));
        sb.Append("## Enum hợp đồng dùng chung — khớp giá trị số của GameTeam.Contracts (wire serialize dạng chuỗi).").Append(Lf);
        sb.Append("class_name ").Append(schema.Name).Append(Lf);
        sb.Append("extends RefCounted").Append(Lf);
        sb.Append(Lf);
        sb.Append("enum {").Append(Lf);
        foreach (EnumMember member in schema.Members)
        {
            sb.Append('\t').Append(GdNaming.ToConstantCase(member.Name)).Append(" = ").Append(member.Value).Append(',').Append(Lf);
        }

        sb.Append('}').Append(Lf);
        return sb.ToString();
    }

    /// <summary>DTO → file <c>class_name &lt;Name&gt; extends Resource</c> + biến typed theo property.</summary>
    public static string EmitDto(DtoSchema schema, string sourceLabel)
    {
        StringBuilder sb = new();
        sb.Append(Header(sourceLabel, schema.Name));
        sb.Append("## Read-model contract (chỉ dữ liệu — không logic/mạng). Parse JSON: Phase 15.").Append(Lf);
        sb.Append("class_name ").Append(schema.Name).Append(Lf);
        sb.Append("extends Resource").Append(Lf);

        if (schema.Properties.Count > 0)
        {
            sb.Append(Lf);
        }

        for (int i = 0; i < schema.Properties.Count; i++)
        {
            DtoProperty prop = schema.Properties[i];
            List<string> notes = ["wire: " + prop.WireName, .. prop.DocNotes];
            sb.Append("## ").Append(string.Join(" | ", notes)).Append(Lf);
            sb.Append("var ").Append(prop.GdName);
            if (prop.Annotation is not null)
            {
                sb.Append(": ").Append(prop.Annotation);
            }

            sb.Append(Lf);
            if (i < schema.Properties.Count - 1)
            {
                sb.Append(Lf);
            }
        }

        return sb.ToString();
    }
}
